[workspace]
members = [
  "icann-rdap-cli",
  "icann-rdap-client",
  "icann-rdap-common",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/icann/icann-rdap"

[workspace.dependencies]

# easy error handling
anyhow = "1.0"

# macros for the builder pattern
buildstructor = "0.5"

# CIDR utilities
cidr-utils = "0.5"

# command line options parser
clap= { version = "4.0", features = [ "std", "derive", "env" ] }

# chrono (time and date library)
chrono = { version = "0.4", features = ["alloc", "std", "clock", "serde"] }

# loads environment variables from the a file
dotenv = "0.15.0"

# futures
futures = "0.3"

# futures-utils
futures-util = "0.3"

# macros to get the git version
git-version = "0.3"

# lazy static initilization
lazy_static = "1.4"

# percent encoding
pct-str = "1.2"

# regular expresions
regex = "1.7"

# http client library
reqwest = {version = "0.11", features = ["json", "stream"]}

# serialization / deserialization library
serde = { version = "1.0", features = [ "derive" ] }

# json serializer
serde_json = "1.0"

# simple log framework
simplelog = { version = "0.12", features = ["paris"] }

# enum utilities
strum = "0.24"
strum_macros = "0.24"

# error macros
thiserror = "1.0"

# tokio async runtime
tokio = { version = "1.21", features = [ "full" ] }

