[package]
name = "icann-rdap-cli"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
#repository = "https://github.com/rust-lang/cargo"
readme = "README.md"
description = """
An RDAP Command Line Interface client.
"""

[[bin]]
name = "rdap"
path = "src/main.rs"
