name: DevTest

on:
  pull_request:
    branches:
      - dev

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check format
      run: cargo fmt --check
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install WASM32
      run: rustup target add wasm32-unknown-unknown
    - name: Check wasm32
      run: cargo check --target wasm32-unknown-unknown -p icann-rdap-client

